### ISSUE TITLE
undefined: goflags.NormalizedStringSlice (library)

### ISSUE THREAD

**Issue by miniboom360** [projectdiscovery/subfinder#562]
**Describe the bug**
When I plan  to use this library as in the readme.md example, it reports some error,like 
undefined: goflags.NormalizedStringSlice && flagSet.NormalizedStringSliceVarP undefined (type *goflags.FlagSet has no field or method NormalizedStringSliceVarP)

in this file: github.com/projectdiscovery/subfinder/v2@v2.5.2/pkg/runner/options.go:41:20:

**Subfinder version**
`subfinder -version 2.5.2`

**Complete command you used to reproduce this**

**Screenshots**
![image](https://user-images.githubusercontent.com/24936258/176607251-cbf857a8-a223-4ded-b548-3907729baf03.png)

**Comment by ehsandeep** [comment]
@miniboom360 should be fixed in the dev version with - https://github.com/projectdiscovery/subfinder/pull/573

**Comment by miniboom360** [comment]
ok,

**Comment by miniboom360** [comment]
i use subfinder in go mod, how i upgrade subfinder's go mod in go mod?

**Comment by thelicato** [comment]
I have the same problem and the command ``go get github.com/projectdiscovery/subfinder/v2/pkg/runner@v2.5.2`` does not fix the problem. On the other hand I can also see that ``goflags`` v1.0 is not released yet.

**Comment by Mzack9999** [comment]
From within your IDE terminal:
```
$ go get -v github.com/projectdiscovery/subfinder/v2@dev
go: downloading github.com/projectdiscovery/subfinder/v2 v2.5.2-0.20220729151422-13583c7f3c31
go: downloading github.com/projectdiscovery/subfinder v0.1.2-0.20220729151422-13583c7f3c31
go: upgraded github.com/projectdiscovery/blackrock v0.0.0-20210415162320-b38689ae3a2e => v0.0.0-20210903102120-5a9d2412d21d
go: upgraded github.com/projectdiscovery/sliceutil v0.0.0-20220225084130-8392ac12fa6d => v0.0.0-20220426000009-1d2b7c02f65c
go: upgraded github.com/projectdiscovery/stringsutil v0.0.0-20220422150559-b54fb5dc6833 => v0.0.0-20220612082425-0037ce9f89f3
go: added github.com/projectdiscovery/subfinder/v2 v2.5.2-0.20220729151422-13583c7f3c31
go: upgraded golang.org/x/mod v0.4.2 => v0.5.1
go: upgraded golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd => v0.0.0-20220624214902-1bab6f366d9e
go: upgraded golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e => v0.0.0-20220520151302-bc2c85ada10a
go: upgraded golang.org/x/tools v0.1.6-0.20210726203631-07bc1bf47fb2 => v0.1.9
```

**Comment by ehsandeep** [comment]
@thelicato @miniboom360 should be fixed as we just published new release of subfinder - https://github.com/projectdiscovery/subfinder/releases/tag/v2.5.3
